[project]
name = "backend"
version = "0.1.0"
description = "backendのソースコード"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.136.3",
    "langchain-google-genai>=4.2.4",
    "python-dotenv>=1.2.2",
    "uvicorn>=0.49.0",
    "torch>=2.11.0",
    "torchvision>=0.26.0",
    "transformers>=5.10.2",
    "accelerate>=1.13.0",
    "langchain-community>=0.4.2",
    "llama-cpp-python>=0.3.28",
    "langchain-ollama>=1.1.0",
    "langchain-chroma>=1.1.0",
    "langchain-huggingface>=1.2.2",
    "sentence-transformers>=5.6.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.15.11",
]

[tool.uv.sources]
torch = [
    { index = "torch-cu128" },
]

[[tool.uv.index]]
name = "torch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.ruff]
line-length = 100
target-version = "py313"
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "alembic",
]

[tool.ruff.lint]
select = [
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "F",      # pyflakes
    "I",      # isort
    "C",      # flake8-comprehensions
    "B",      # flake8-bugbear
    "UP",     # pyupgrade
]
ignore = ["E501", "C901", "UP015"]

[tool.ruff.lint.isort]
known-first-party = ["src"]
combine-as-imports = true


